"""
Generate publication figures for the paper.

Figures generated:
  - fig2_bandstructure_m5.pdf  (Fig 2: band structure Γ-X-M-R-Γ)
  - fig3_meshes_m5.pdf         (Fig 3: mesh wireframes)

Note: fig1_convergence_m5.pdf is generated by test_convergence.py data
      and was produced separately.

Usage:
    cd /path/to/st_bloch_exactness
    OPENBLAS_NUM_THREADS=1 OMP_NUM_THREADS=1 .venv/bin/python tests/make_figures.py

Expected output (macOS, Python 3.9.6, SciPy 1.13):

    ======================================================================
    FIGURE GENERATION
    Paper: Figures 2, 3
    ======================================================================

    --- Figure 2: Band structure ---
      121 k-points, 8 bands
      Saved .../paper/fig2_bandstructure_m5.pdf

    --- Figure 3: Mesh visualization ---
      Kelvin: 36 segments
      Random Voronoi: 82 segments
      Saved .../paper/fig3_meshes_m5.pdf

    All figures generated.
"""

import sys, os
import numpy as np
from scipy.spatial import Voronoi
from scipy.linalg import eigh

sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', 'src'))

from physics.hodge import build_kelvin_with_dual_info, build_hodge_stars_voronoi
from physics.gauge_bloch import compute_edge_shifts, build_d0_bloch, build_d1_bloch_exact
from physics.bloch import build_d1_bloch_standard, compute_edge_crossings, build_edge_lookup

import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
from matplotlib.gridspec import GridSpec
from mpl_toolkits.mplot3d.art3d import Line3DCollection

PAPER_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', 'paper')


# ── Figure 2: Band structure Γ-X-M-R-Γ ──────────────────────────────────

def solve_at_k(k, V, E, F, L_vec, L, star1, star2, shifts, crossings, edge_lookup, n_bands=10):
    """Compute first n_bands physical eigenvalues + ||d1d0|| at given k."""
    d0_k = build_d0_bloch(V, E, k, L_vec, shifts)

    d1_ex = build_d1_bloch_exact(V, E, F, k, L_vec, d0_k)
    K_ex = d1_ex.conj().T @ np.diag(star2) @ d1_ex
    K_ex = 0.5 * (K_ex + K_ex.conj().T)
    M = np.diag(star1)
    eigs_ex = np.sort(np.real(eigh(K_ex, M, eigvals_only=True)))
    thresh_ex = max(np.max(np.abs(eigs_ex)) * 1e-12, 1e-14)
    phys_ex = eigs_ex[np.abs(eigs_ex) >= thresh_ex]
    norm_ex = np.linalg.norm(d1_ex @ d0_k)

    d1_st = build_d1_bloch_standard(V, E, F, L, k, edge_lookup, crossings)
    K_st = d1_st.conj().T @ np.diag(star2) @ d1_st
    K_st = 0.5 * (K_st + K_st.conj().T)
    eigs_st = np.sort(np.real(eigh(K_st, M, eigvals_only=True)))
    thresh_st = max(np.max(np.abs(eigs_st)) * 1e-12, 1e-14)
    phys_st = eigs_st[np.abs(eigs_st) >= thresh_st]
    norm_st = np.linalg.norm(d1_st @ d0_k)

    return phys_ex[:n_bands], phys_st[:n_bands], norm_ex, norm_st


def build_bz_path(n_per_segment=15):
    """Build Γ-X-M-R-Γ path in fractional coordinates of 2π/L."""
    G = np.array([0.0, 0.0, 0.0])
    X = np.array([0.5, 0.0, 0.0])
    M = np.array([0.5, 0.5, 0.0])
    R = np.array([0.5, 0.5, 0.5])

    segments = [('Γ', 'X', G, X), ('X', 'M', X, M),
                ('M', 'R', M, R), ('R', 'Γ', R, G)]

    fracs, labels, label_positions = [], [], []
    cumulative_dist = 0.0

    for i, (name_a, name_b, pa, pb) in enumerate(segments):
        seg_len = np.linalg.norm(pb - pa)
        for j in range(n_per_segment):
            t = j / n_per_segment
            fracs.append(pa + t * (pb - pa))
            labels.append(cumulative_dist + t * seg_len)
        if i == 0:
            label_positions.append((0.0, name_a))
        label_positions.append((cumulative_dist + seg_len, name_b))
        cumulative_dist += seg_len

    fracs.append(G)
    labels.append(cumulative_dist)
    return np.array(fracs), np.array(labels), label_positions


def make_fig_bandstructure():
    """Fig 2: Band structure along Γ-X-M-R-Γ."""
    print("\n--- Figure 2: Band structure ---")

    data = build_kelvin_with_dual_info(N=2, L_cell=4.0)
    V, E, F = data['V'], data['E'], data['F']
    L, L_vec = data['L'], data['L_vec']

    star1, star2 = build_hodge_stars_voronoi(data)
    shifts = compute_edge_shifts(V, E, L_vec)
    crossings = compute_edge_crossings(V, E, L)
    edge_lookup = build_edge_lookup(E, crossings)

    k_scale = 2 * np.pi / L
    n_per_seg, n_bands = 30, 8
    fracs, path_dists, label_positions = build_bz_path(n_per_segment=n_per_seg)

    print(f"  {len(fracs)} k-points, {n_bands} bands")

    bands_exact, bands_std = [], []
    norms_exact, norms_std = [], []

    for frac in fracs:
        k = k_scale * (frac if np.linalg.norm(frac) > 1e-10 else np.array([0.001, 0.001, 0.001]))
        phys_ex, phys_st, norm_ex, norm_st = solve_at_k(
            k, V, E, F, L_vec, L, star1, star2, shifts, crossings, edge_lookup, n_bands)
        bands_exact.append(phys_ex)
        bands_std.append(phys_st)
        norms_exact.append(norm_ex)
        norms_std.append(norm_st)

    bands_exact = np.array(bands_exact)
    bands_std = np.array(bands_std)

    plt.rcParams.update({
        "font.size": 10, "axes.titlesize": 10, "axes.labelsize": 10,
        "legend.fontsize": 8, "lines.linewidth": 1.5, "pdf.fonttype": 42,
    })

    fig = plt.figure(figsize=(6.8, 5.0))
    gs = GridSpec(2, 2, height_ratios=[3, 1], hspace=0.35, wspace=0.08)
    ax1 = fig.add_subplot(gs[0, 0])
    ax2 = fig.add_subplot(gs[0, 1], sharey=ax1)
    ax3 = fig.add_subplot(gs[1, :])

    tick_pos = [p for p, n in label_positions]
    tick_lab = [n for p, n in label_positions]

    for b in range(n_bands):
        color, lw = ('C0', 1.8) if b < 2 else ('black', 0.7)
        ax1.plot(path_dists, bands_exact[:, b], '-', color=color, lw=lw)
    ax1.set_ylabel(r'$\omega^2$')
    ax1.set_title(r'(a) Exactness preserved: $d_1 d_0 = 0$')
    ax1.set_xlim(path_dists[0], path_dists[-1])
    ax1.set_ylim(0, 0.65)
    ax1.set_xticks(tick_pos)
    ax1.set_xticklabels(tick_lab)
    for p in tick_pos:
        ax1.axvline(x=p, color='0.85', ls='-', lw=0.5)

    for b in range(n_bands):
        color, lw = ('C3', 1.8) if b < 2 else ('black', 0.7)
        ax2.plot(path_dists, bands_std[:, b], '-', color=color, lw=lw)
    ax2.set_title(r'(b) Exactness broken: $d_1^{\mathrm{std}} d_0 \neq 0$')
    ax2.set_xlim(path_dists[0], path_dists[-1])
    ax2.set_xticks(tick_pos)
    ax2.set_xticklabels(tick_lab)
    plt.setp(ax2.get_yticklabels(), visible=False)
    for p in tick_pos:
        ax2.axvline(x=p, color='0.85', ls='-', lw=0.5)

    ax3.semilogy(path_dists, np.array(norms_std), '-', color='C3', lw=1.5,
                 label=r'$\|d_1^{\mathrm{std}} d_0\|$')
    ax3.semilogy(path_dists, np.array(norms_exact) + 1e-20, '-', color='C0', lw=1.5,
                 label=r'$\|d_1^{\mathrm{exact}} d_0\|$')
    ax3.set_ylabel(r'$\|d_1 d_0\|$')
    ax3.set_xlim(path_dists[0], path_dists[-1])
    ax3.set_ylim(1e-17, 50)
    ax3.set_xticks(tick_pos)
    ax3.set_xticklabels(tick_lab)
    for p in tick_pos:
        ax3.axvline(x=p, color='0.85', ls='-', lw=0.5)
    ax3.legend(loc='center right')
    ax3.set_title(r'(c) Exactness violation along BZ path')

    outpdf = os.path.join(PAPER_DIR, 'fig2_bandstructure_m5.pdf')
    fig.savefig(outpdf, bbox_inches='tight')
    print(f"  Saved {outpdf}")
    plt.close()


# ── Figure 3: Mesh wireframes ───────────────────────────────────────────

def collect_interior_segments(V, E, L, clip_box=None):
    segments = []
    for (i, j) in E:
        p1, p2 = V[i], V[j]
        if np.any(np.abs(p2 - p1) > L / 2):
            continue
        if clip_box is not None:
            lo, hi = clip_box
            if np.any(p1 < lo) or np.any(p1 > hi) or np.any(p2 < lo) or np.any(p2 > hi):
                continue
        segments.append([p1, p2])
    return segments


def build_random_voronoi_segments(n_cells, L, seed, clip_box):
    np.random.seed(seed)
    pts = np.random.uniform(0, L, size=(n_cells, 3))

    all_pts = [pts]
    for dx in (-1, 0, 1):
        for dy in (-1, 0, 1):
            for dz in (-1, 0, 1):
                if dx == 0 and dy == 0 and dz == 0:
                    continue
                all_pts.append(pts + np.array([dx, dy, dz]) * L)
    all_pts = np.vstack(all_pts)

    vor = Voronoi(all_pts)
    lo, hi = clip_box
    selected = {idx for idx in range(n_cells)
                if np.all(all_pts[idx] >= lo) and np.all(all_pts[idx] <= hi)}

    seen_edges = set()
    segments = []
    for face_idx, ridge in enumerate(vor.ridge_vertices):
        if -1 in ridge:
            continue
        c1, c2 = vor.ridge_points[face_idx]
        if c1 not in selected and c2 not in selected:
            continue
        n = len(ridge)
        for k in range(n):
            edge_key = (min(ridge[k], ridge[(k + 1) % n]),
                        max(ridge[k], ridge[(k + 1) % n]))
            if edge_key in seen_edges:
                continue
            seen_edges.add(edge_key)
            segments.append([vor.vertices[ridge[k]], vor.vertices[ridge[(k + 1) % n]]])
    return segments


def plot_mesh_3d(ax, segments, title, view_box, color='0.25', lw=0.7):
    lc = Line3DCollection(segments, colors=color, linewidths=lw, zorder=1)
    ax.add_collection3d(lc)

    lo, hi = view_box
    pad = (hi - lo) * 0.08
    ax.set_xlim(lo - pad, hi + pad)
    ax.set_ylim(lo - pad, hi + pad)
    ax.set_zlim(lo - pad, hi + pad)

    ax.set_title(title, fontsize=9, pad=0)
    for a in [ax.xaxis, ax.yaxis, ax.zaxis]:
        a.set_ticks([])
        a.pane.fill = False
        a.pane.set_edgecolor((0.9, 0.9, 0.9, 1.0))
        a.line.set_color((0.9, 0.9, 0.9, 1.0))
    ax.grid(False)
    ax.view_init(elev=18, azim=-55)


def make_fig_meshes():
    """Fig 3: Kelvin foam + Random Voronoi wireframes."""
    print("\n--- Figure 3: Mesh visualization ---")

    data_k = build_kelvin_with_dual_info(N=2, L_cell=4.0)
    V_k, E_k, L_k = data_k['V'], data_k['E'], data_k['L']
    clip_k = (1.5, 6.5)
    seg_k = collect_interior_segments(V_k, E_k, L_k, clip_box=clip_k)
    print(f"  Kelvin: {len(seg_k)} segments")

    seg_r = build_random_voronoi_segments(n_cells=20, L=10.0, seed=42,
                                           clip_box=(2.0, 8.0))
    print(f"  Random Voronoi: {len(seg_r)} segments")

    plt.rcParams.update({"font.size": 9, "axes.titlesize": 9, "pdf.fonttype": 42})
    fig = plt.figure(figsize=(6.8, 3.0))

    ax1 = fig.add_subplot(121, projection='3d')
    plot_mesh_3d(ax1, seg_k, r'(a) Kelvin foam', view_box=clip_k, color='0.20')

    ax2 = fig.add_subplot(122, projection='3d')
    plot_mesh_3d(ax2, seg_r, r'(b) Random Voronoi', view_box=(2.0, 8.0), color='0.20')

    fig.subplots_adjust(left=0.01, right=0.99, bottom=0.01, top=0.93, wspace=0.02)

    outpdf = os.path.join(PAPER_DIR, 'fig3_meshes_m5.pdf')
    fig.savefig(outpdf, bbox_inches='tight', dpi=300)
    print(f"  Saved {outpdf}")
    plt.close()


def main():
    print("=" * 70)
    print("FIGURE GENERATION")
    print("Paper: Figures 2, 3")
    print("=" * 70)

    make_fig_bandstructure()
    make_fig_meshes()

    print("\nAll figures generated.")


if __name__ == '__main__':
    main()
    print("\nDone.")
